### ISSUE TITLE
Start farming forever

### ISSUE THREAD

**Issue by Nevershay** [Dawjaw/HoeUtilitiesV2#1]
The XP info is constantly displaying 'Start farming' when I farm for like 20min+

**Comment by Dawjaw** [comment]
Do you have your skill api enabled?

**Comment by Nevershay** [comment]
Ye I have all api enabled

**Comment by Dawjaw** [comment]
Is there any error that pops up when you run the command
/ct console js
in the chat

**Comment by Nevershay** [comment]
it puts me this:
undefined
undefined
text input value:

**Comment by Dawjaw** [comment]
Hmm seems like those outputs are not related to your issue.
Can you tell me what version of CT you use in addition with which version of HoeUtilities
What's the output of /hu2debug
can you try reinstalling it by opening the install folder via "/ct files" and then manaully deleting HoeUtilitiesV2, requestV2 and PromiseV2

**Comment by Nevershay** [comment]
I found the problem. I was using an old version of DSM and I don't know why it wasn't working with it. Sorry for the inconvenience, and thanks for your help.
